version: '3.8'

services:
  identic_flux_api:
    build: .
    ports:
      - "8000:8000"     # API
      - "8188:8188"     # ComfyUI (optional)
    volumes:
      - comfyui_data:/ComfyUI
      - ./output:/ComfyUI/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - HF_TOKEN=${HF_TOKEN}

volumes:
  comfyui_data:
