version: '3.8'

services:
  identic_flux_api:
    build: .
    ports:
      - "8000:8000"
      - "8188:8188"  # Optional ComfyUI port
    volumes:
      - ./comfyui_data:/ComfyUI                # Persistent ComfyUI base
      - ./output:/ComfyUI/output               # Generated outputs
      # Optional model cache (recommended):
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub
    deploy: 
      resources: 
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - HF_TOKEN=${HF_TOKEN}
