version: '3.8'

services:
  flux-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - workspace:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - HF_TOKEN=${HF_TOKEN}

volumes:
  workspace: